CXXFLAGS=/EHsc /bigobj /std:c++17 /Ox /D_HAS_AUTO_PTR_ETC=1 $(CXXFLAGS)
EXECUTABLE=diff.exe
INCLUDE=..\..\..;$(INCLUDE)
OBJECTS=$(SOURCES:.cpp=.obj)
SOURCES=main.cpp

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CXX) /Fe:$(EXECUTABLE) $(OBJECTS) $(LIBS)

.cpp.obj:
	$(CXX) -c $(CXXFLAGS) $<

clean:
	del *.obj *.exp *.lib $(EXECUTABLE)
